### ISSUE TITLE
Diagrammi UML

### ISSUE THREAD

**Issue by Wordluc** [Wordluc/Progetto-Ingegneria-Soft#9]
Necessità di aggiornamento diagrammi uml 
I diagrammi richiesti sono:
   sequenza 
   stati
   casi d'uso

**Comment by SerraG99** [comment]
[Diagrammi.zip](https://github.com/Wordluc/Progetto-Ingegneria-Soft/files/10354003/Diagrammi.zip)
Diagrammi casi duso + diagramma di sequenza
